export const GET_ALL_SUPPLIERS = "GET_ALL_SUPPLIERS";
export const CREATE_A_SUPPLIER = "CREATE_A_SUPPLIER";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_A_CATEGORY = "CREATE_A_CATEGORY";
export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
